"""Telegram Bot API v10 native Python SDK — direct HTTP client.

Complete drop-in replacement for python-telegram-bot.
Communicates directly with api.telegram.org over HTTP(S).
Supports all Bot API v10 features (May 8, 2026).
"""

from __future__ import annotations

# Re-export all types for PTB-compatible imports
from telegram._types import (
    Animation,
    Audio,
    TelegramObject,
    BotCommand,
    BotCommandScopeAllChatAdministrators,
    BotCommandScopeAllGroupChats,
    BotCommandScopeAllPrivateChats,
    BotCommandScopeChat,
    BotCommandScopeChatAdministrators,
    BotCommandScopeChatMember,
    BotCommandScopeDefault,
    BusinessConnection,
    BusinessIntro,
    BusinessLocation,
    BusinessOpeningHours,
    BusinessOpeningHoursInterval,
    BusinessMessagesDeleted,
    CallbackQuery,
    Chat,
    ChatAdministratorRights,
    ChatBoost,
    ChatBoostAdded,
    ChatBoostRemoved,
    ChatBoostUpdated,
    ChatFullInfo,
    ChatInviteLink,
    ChatJoinRequest,
    ChatLocation,
    ChatMember,
    ChatMemberAdministrator,
    ChatMemberBanned,
    ChatMemberLeft,
    ChatMemberMember,
    ChatMemberOwner,
    ChatMemberRestricted,
    ChatMemberUpdated,
    ChatPermissions,
    ChosenInlineResult,
    Contact,
    Dice,
    Document,
    EncryptedPassportElement,
    File,
    ForceReply,
    ForumTopic,
    ForumTopicClosed,
    ForumTopicCreated,
    ForumTopicReopened,
    Game,
    GameHighScore,
    GeneralForumTopicHidden,
    GeneralForumTopicUnhidden,
    Gift,
    Gifts,
    Giveaway,
    GiveawayCreated,
    GiveawayWinners,
    GuestAvatar,
    InlineKeyboardButton,
    InlineKeyboardMarkup,
    InlineQuery,
    InputMedia,
    InputMediaAnimation,
    InputMediaAudio,
    InputMediaDocument,
    InputMediaPhoto,
    InputMediaVideo,
    Invoice,
    KeyboardButton,
    KeyboardButtonPollType,
    KeyboardButtonRequestChat,
    KeyboardButtonRequestUser,
    LabeledPrice,
    LinkPreviewOptions,
    LivePhoto,
    Location,
    ManagedBotInChat,
    ManagedBotUpdate,
    MaskPosition,
    MenuButton,
    MenuButtonCommands,
    MenuButtonDefault,
    MenuButtonWebApp,
    Message,
    MessageAutoDeleteTimerChanged,
    MessageEntity,
    MessageReactionCountUpdated,
    MessageReactionUpdated,
    PaidMedia,
    PaidMediaInfo,
    PaidMediaPhoto,
    PaidMediaPreviewed,
    PaidMediaVideo,
    PassportData,
    PassportFile,
    PhotoSize,
    Poll,
    PollAnswer,
    PollOption,
    PreCheckoutQuery,
    ProximityAlertTriggered,
    PurchasedPaidMedia,
    ReactionCount,
    ReactionType,
    ReactionTypeEmoji,
    ReactionTypePaid,
    ReplyKeyboardMarkup,
    ReplyKeyboardRemove,
    ReplyParameters,
    SentGuestMessage,
    ShippingAddress,
    ShippingOption,
    ShippingQuery,
    StarTransaction,
    StarTransactions,
    Sticker,
    StickerSet,
    SuccessfulPayment,
    Update,
    User,
    Venue,
    Video,
    VideoNote,
    Voice,
    WebAppInfo,
    WebhookInfo,
    WriteAccessAllowed,
)

# Re-export bot
from telegram._bot import Bot
from telegram import _types as _types_module


def __getattr__(name: str):
    try:
        value = getattr(_types_module, name)
    except AttributeError as exc:
        raise AttributeError(f"module 'telegram' has no attribute {name!r}") from exc
    globals()[name] = value
    return value

__all__ = [
    "TelegramObject",
    "Animation", "Audio", "BotCommand",
    "BotCommandScopeAllChatAdministrators", "BotCommandScopeAllGroupChats",
    "BotCommandScopeAllPrivateChats", "BotCommandScopeChat",
    "BotCommandScopeChatAdministrators", "BotCommandScopeChatMember",
    "BotCommandScopeDefault",
    "BusinessConnection", "BusinessIntro", "BusinessLocation",
    "BusinessOpeningHours", "BusinessOpeningHoursInterval",
    "BusinessMessagesDeleted",
    "CallbackQuery", "Chat", "ChatAdministratorRights",
    "ChatBoost", "ChatBoostAdded", "ChatBoostRemoved", "ChatBoostUpdated",
    "ChatFullInfo", "ChatInviteLink", "ChatJoinRequest", "ChatLocation",
    "ChatMember", "ChatMemberAdministrator", "ChatMemberBanned",
    "ChatMemberLeft", "ChatMemberMember", "ChatMemberOwner",
    "ChatMemberRestricted", "ChatMemberUpdated", "ChatPermissions",
    "ChosenInlineResult", "Contact", "Dice", "Document",
    "EncryptedPassportElement", "File", "ForceReply",
    "ForumTopic", "ForumTopicClosed", "ForumTopicCreated", "ForumTopicReopened",
    "Game", "GameHighScore", "GeneralForumTopicHidden", "GeneralForumTopicUnhidden",
    "Gift", "Gifts", "Giveaway", "GiveawayCreated", "GiveawayWinners",
    "GuestAvatar",
    "InlineKeyboardButton", "InlineKeyboardMarkup", "InlineQuery",
    "InputMedia", "InputMediaAnimation", "InputMediaAudio",
    "InputMediaDocument", "InputMediaPhoto", "InputMediaVideo",
    "Invoice",
    "KeyboardButton", "KeyboardButtonPollType", "KeyboardButtonRequestChat",
    "KeyboardButtonRequestUser",
    "LabeledPrice", "LinkPreviewOptions", "LivePhoto", "Location",
    "ManagedBotInChat", "ManagedBotUpdate", "MaskPosition",
    "MenuButton", "MenuButtonCommands", "MenuButtonDefault", "MenuButtonWebApp",
    "Message", "MessageAutoDeleteTimerChanged", "MessageEntity",
    "MessageReactionCountUpdated", "MessageReactionUpdated",
    "PaidMedia", "PaidMediaInfo", "PaidMediaPhoto", "PaidMediaPreviewed",
    "PaidMediaVideo",
    "PassportData", "PassportFile", "PhotoSize",
    "Poll", "PollAnswer", "PollOption",
    "PreCheckoutQuery", "ProximityAlertTriggered", "PurchasedPaidMedia",
    "ReactionCount", "ReactionType", "ReactionTypeEmoji", "ReactionTypePaid",
    "ReplyKeyboardMarkup", "ReplyKeyboardRemove", "ReplyParameters",
    "SentGuestMessage",
    "ShippingAddress", "ShippingOption", "ShippingQuery",
    "StarTransaction", "StarTransactions",
    "Sticker", "StickerSet", "SuccessfulPayment",
    "Update", "User",
    "Venue", "Video", "VideoNote", "Voice",
    "WebAppInfo", "WebhookInfo", "WriteAccessAllowed",
    "Bot",
]

__all__.extend(name for name in _types_module._GENERIC_TYPE_NAMES if name not in __all__)
